### PR TITLE
Add react rails

### PR DESCRIPTION
**Pull request by MesakDuduCoder**
## In this pull request
* I added react to my rails app using webpack
* I created postgres database with a greeting table which has some greetings
* I added router and redux to my react 
* I added a rails api to a show a greeting on a react component

### CODE REVIEW

**Comment by topeogunleye** [comment]
@MesakDuduCoder, please can you tell me the command to run your project locally?

**Comment by MesakDuduCoder** [comment]
> @MesakDuduCoder, please can you tell me the command to run your project locally?

@topeogunleye rails server

**Comment by MesakDuduCoder** [comment]
> > > @MesakDuduCoder, please can you tell me the command to run your project locally?
> > 
> > 
> > @topeogunleye rails server
> 
> How about the react application?. Please can you run `./bin/dev` locally and send a screenshot. let me see if it works

Screenshot (161)
Screenshot (162)
yes its working when i did on git bash before i tried to do on vscode terminal and i could not

**Comment by topeogunleye** [comment]
> > > > @MesakDuduCoder, please can you tell me the command to run your project locally?
> > > 
> > > 
> > > @topeogunleye rails server
> > 
> > 
> > How about the react application?. Please can you run `./bin/dev` locally and send a screenshot. let me see if it works
> 
> Screenshot (161) Screenshot (162) yes its working when i did on git bash before i tried to do on vscode terminal and i could not

Thank you for confirming that it's working. 👍

**Review by topeogunleye — APPROVED** [review]
Hi @MesakDuduCoder, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

dwayne-the-rock

## (Highlights) Good Points: 💪 

1. **Webpack Setup 🛠️**: 
   - You followed the ["Webpack" section](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/lessons/rails_and_webpack.md) diligently. The configurations are spot on! 👌
  
2. **Gem and Dependencies 📦**:
   - The `jsbundling-rails` gem was rightly used. Good work! 
   - I also noticed the `react-dom` and `babel-loader` dependencies in your `package.json`. Great attention to detail there! ✔️

3. **Configuration Files 📁**:
   - Your `babel.config.js` and `webpack.config.js` are set up as illustrated in the tutorial. Perfect! 

4. **Rails Backend 🚂**:
   - Your API endpoint for random greetings is correctly set up. I verified this by checking the `routes.rb` and the corresponding controller. 
   - The database table for storing different greetings is intact. Your migrations, model and the greetings created via the rails console are on point! 👍
   - The static root route you've created is just perfect. The associated view with `<div id="root">` shows you've set the foundation right for your React integration. 

5. **React and Redux Frontend 🎨**:
   - Your `app/javascript/application.js` houses all the necessary configurations and components.
   - The `App` component with the routes from `react-router` and the `Greeting` component are well-constructed. 🌟
   - The way you've set up the store, action, and reducer with a placeholder URL shows forward-thinking. Kudos!
   
6. **Integration 🔄**:
   - Running the Rails API on my machine using `./bin/dev` and connecting it with the React app demonstrated a seamless integration. I was thrilled to see the random greeting displayed from your API through the React frontend. 🎉

In summary, you've done an amazing job combining Rails and React, ensuring each technology plays to its strengths. Keep up the good work, and continue with this zeal in your future projects! 🚀👏🎊

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
👉 One optional suggestion for improvement is to follow the convention for naming your branch. Usually, branch names should use the past tense verb to indicate that the feature has been implemented. For example, instead of `add-react-rails`, you could use `added-react-rails`. 
This would make your branch name more consistent and clear for future pull requests.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> Thank you for your kind and thorough review @topeogunleye, I appreciate it.

@MesakDuduCoder, You're welcome! I'm glad you found the review helpful. Keep up the great work, and don't hesitate to reach out if you have any questions or need further feedback. 😊👍

**Pull request merged**
